### PR TITLE
Scraping Scripts to get Notifications

### PR DESCRIPTION
**Pull request by Aahanbhatt**

### CODE REVIEW

**Comment by tapaswenipathak** [comment]
@Aahanbhatt When I run the scripts I get the following error, can you please document it somewhere, what has to be passed? A docstring on top of the file will be good.

```
kt@kt-Inspiron-3542:~/Scrapers$ python Ndtv.py 
Traceback (most recent call last):
  File "Ndtv.py", line 22, in <module>
    getnotif("Top stories",items.text)
  File "Ndtv.py", line 8, in getnotif
    notif=Notify.Notification.new(title,message)
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 72, in constructor
    return info.invoke(cls, *args, **kwargs)
TypeError: new() takes exactly 3 arguments (2 given)
```

**Comment by tapaswenipathak** [comment]
@Aahanbhatt Great that you have added the docstring. Error is not related to some installations but to the number of arguments you are passing in the call to

```
notif=Notify.Notification.new(title,message)
```

It needs three arguments and you are passing two. Tech.py is working fine. 

Thanks for the pull request. I will clean up things after merging.

**Comment by Aahanbhatt** [comment]
Cool. Thank you so much, it helps for noobs  like me :)

**Comment by tapaswenipathak** [comment]
No problem. :)

**Pull request merged**
